
name: Build and test

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  build-and-test:
    uses: RhyVis/GTNH-Actions-Workflows/.github/workflows/build-and-test.yml@master
    secrets: inherit
